name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      
env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: weatherreport
 
jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with: 
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}
    
    - name: Docker Build
      run: |-
        gcloud config set project ${{ secrets.RUN_PROJECT }}
        gcloud builds submit --tag gcr.io/${{ secrets.RUN_PROJECT }}/${{ secrets.GCP_APPLICATION }} WeatherReport/.
        gcloud config set run/region us-central1
        
      #Deploy image to cloud run
    - name: CloudRun Deploy
      run: |-
        gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.RUN_PROJECT }}/${{ secrets.GCP_APPLICATION }} \
          --platform "managed" \
          --allow-unauthenticated
