name: Build and Deploy to Cloud Run

on: [push, pull_request]
      
env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: weatherreport
 
jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Determine version
      uses: extenda/actions/conventional-version@v0
      id: semver
      with:
        build-number: ${{ github.run_number }}
    - name: echo
      run: echo ${{ github.run_number }}
      
    - name: Create release
      uses: extenda/actions/conventional-release@v0
      id: release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish release
      run: |
          npm ci
          npm version ${{ steps.release.outputs.version }} --no-git-tag-version
          npm publish
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build dotnet solution
      run: |
        dotnet build WeatherReport.sln --configuration Release /p:Version=${{ steps.semver.outputs.semver }}
    - name: Test
      run: dotnet test --no-build --verbosity normal

